### ISSUE TITLE
CSRF Tests Fail for form and CSRF extension. 

### ISSUE THREAD

**Issue by crood58** [Quart-Addons/quart-wtf#3]
This has also been posted on StackOverflow @ https://stackoverflow.com/questions/73436212/csrf-test-failure-for-wtforms-extension-for-quart

Tests are failing for testing the following test function:

```
@pytest.mark.asyncio
async def test_form_csrf(app, client):
    """
    Test form CSRF.
    """
    @app.route("/", methods=["GET", "POST"])
    async def index():
        form = await QuartForm.create_form()

        if await form.validate_on_submit():
            return "good"

        if form.errors:
            return form.csrf_token.errors[0]

        return form.csrf_token.current_token

    async with app.app_context():
        response = await client.get("/")
        assert await response.get_data(as_text=True) == g.csrf_token

        response = await client.post("/")
        assert  await response.get_data(as_text=True) == "The CSRF token is missing."

        response = await client.post("/", data={"csrf_token": g.csrf_token})
        assert await response.get_data(as_text=True) == "good"
```

Also the majority of the tests fail for the CSRF extension:

```
@pytest.fixture
def app(app):
    CSRFProtect(app)

    @app.route("/", methods=["GET", "POST"])
    async def index():
        pass

    @app.after_request
    async def add_csrf_header(response):
        response.headers.set("X-CSRF-Token", generate_csrf())
        return response

    return app


@pytest.fixture
def csrf(app) -> CSRFProtect:
    return app.extensions["csrf"]

@pytest.mark.asyncio
async def test_render_token(app):
    async with app.test_request_context("/"):
        token = generate_csrf()
        assert await render_template_string("{{ csrf_token() }}") == token

@pytest.mark.asyncio
async def test_protect(app, client):
    #await app.startup()

    async with app.app_context():
        #response = await client.post("/")
        #assert response.status_code == 400
        #assert TOKEN_MISSING in await response.get_data(as_text=True)

        app.config["WTF_CSRF_ENABLED"] = False
        response = await client.post("/")
        assert await response.get_data() == b""
        app.config["WTF_CSRF_ENABLED"] = True

        app.config["WTF_CSRF_CHECK_DEFAULT"] = False
        response = await client.post("/")
        assert await response.get_data() == b""
        app.config["WTF_CSRF_CHECK_DEFAULT"] = True

        assert await client.options("/").status_code == 200
        assert await client.post("/not-found").status_code == 404

        response = await client.get("/")
        assert response.status_code == 200
        token = response.headers["X-CSRF-Token"]
        assert await client.post("/", data={"csrf_token": token}).status_code == 200
        assert await client.post("/", data={"prefix-csrf_token": token}).status_code == 200
        assert await client.post("/", data={"prefix-csrf_token": ""}).status_code == 400
        assert await client.post("/", headers={"X-CSRF-Token": token}).status_code == 200

@pytest.mark.asyncio
async def test_same_origin(app, client):
    await app.startup()
    response = await client.get("/")
    token = response.headers["X-CSRF-Token"]
    headers = {
        "url": "https://localhost",
        "X-CSRF-Token": token
    }
    response = await client.post("/", headers=headers)
    data = await response.get_data(as_text=True)
    assert REFERRER_HEADER in data

    response = await client.post(
        "/",
        base_url="https://localhost",
        headers={"X-CSRF-Token": token, "Referer": "http://localhost/"},
    )
    data = await response.get_data(as_text=True)
    assert REFERRER_HOST in data

    response = await client.post(
        "/",
        base_url="https://localhost",
        headers={"X-CSRF-Token": token, "Referer": "https://other/"},
    )
    data = await response.get_data(as_text=True)
    assert REFERRER_HOST in data

    response = await client.post(
        "/",
        base_url="https://localhost",
        headers={"X-CSRF-Token": token, "Referer": "https://localhost:8080/"},
    )
    data = await response.get_data(as_text=True)
    assert REFERRER_HOST in data

    response = await client.post(
        "/",
        base_url="https://localhost",
        headers={"X-CSRF-Token": token, "Referer": "https://localhost/"},
    )
    assert response.status_code == 200

@pytest.mark.asyncio
async def test_form_csrf_short_circuit(app, client):
    @app.route("/skip", methods=["POST"])
    async def skip():
        assert g.get("csrf_valid")
        # don't pass the token, then validate the form
        # this would fail if CSRFProtect didn't run
        form = QuartForm(formdata=None)
        assert await form.validate()
    response = await client.get("/")
    token = response.headers["X-CSRF-Token"]
    print(token)
    response = await client.post("/skip", headers={"X-CSRF-Token": token})
    assert response.status_code == 200

@pytest.mark.asyncio
async def test_exempt_view(app, csrf, client):
    @app.route("/exempt", methods=["POST"])
    @csrf.exempt
    async def exempt():
        pass

    response = await client.post("/exempt")
    assert response.status_code == 200

    csrf.exempt("test_csrf_extension.index")
    response = await client.post("/")
    assert response.status_code == 200

@pytest.mark.asyncio
async def test_manual_protect(app, csrf, client):
    @app.route("/manual", methods=["GET", "POST"])
    @csrf.exempt
    async def manual():
        await csrf.protect()

    response = await client.get("/manual")
    assert response.status_code == 200

    response = await client.post("/manual")
    assert response.status_code == 400

@pytest.mark.asyncio
async def test_exempt_blueprint(app, csrf, client):
    bp = Blueprint("exempt", __name__, url_prefix="/exempt")
    csrf.exempt(bp)

    @bp.route("/", methods=["POST"])
    async def index():
        pass

    app.register_blueprint(bp)
    response = await client.post("/exempt/")
    assert response.status_code == 200

@pytest.mark.asyncio
async def test_error_handler(app, client):
    @app.errorhandler(CSRFError)
    async def handle_csrf_error(error):
        return error.description.lower()

    response = await client.post("/")
    assert await response.get_data(as_text=True) == TOKEN_MISSING

@pytest.mark.asyncio
async def test_validate_error_logged(client, monkeypatch):
    messages = []

    def assert_info(message):
        messages.append(message)

    monkeypatch.setattr(logger, "info", assert_info)

    await client.post("/")
    assert len(messages) == 1
    assert messages[0] == "The CSRF token is missing."

```
I believe that this is more of an issue with the tests than the actual code.

**Comment by yasunori** [comment]
At csrf.py, do you want to set default values?
How about the following?
```
app.config.setdefault("WTF_CSRF_ENABLED", DEFAULT_ENABLED)
app.config.setdefault("WTF_CSRF_CHECK_DEFAULT", DEFAULT_CHECK_DEFAULT)
app.config.setdefault("WTF_CSRF_METHODS", DEFAULT_SUBMIT_METHODS)
app.config.setdefault("WTF_CSRF_FIELD_NAME", DEFAULT_CSRF_FIELD_NAME)
app.config.setdefault("WTF_CSRF_HEADERS", DEFAULT_CSRF_HEADERS)
app.config.setdefault("WTF_CSRF_TIME_LIMIT", DEFAULT_CSRF_TIME_LIMIT)
app.config.setdefault("WTF_CSRF_SSL_STRICT", DEFAULT_CSRF_SSL_STRICT)
```

**Comment by crood58** [comment]
> At csrf.py, do you want to set default values? How about the following?
> 
> ```
> app.config.setdefault("WTF_CSRF_ENABLED", DEFAULT_ENABLED)
> app.config.setdefault("WTF_CSRF_CHECK_DEFAULT", DEFAULT_CHECK_DEFAULT)
> app.config.setdefault("WTF_CSRF_METHODS", DEFAULT_SUBMIT_METHODS)
> app.config.setdefault("WTF_CSRF_FIELD_NAME", DEFAULT_CSRF_FIELD_NAME)
> app.config.setdefault("WTF_CSRF_HEADERS", DEFAULT_CSRF_HEADERS)
> app.config.setdefault("WTF_CSRF_TIME_LIMIT", DEFAULT_CSRF_TIME_LIMIT)
> app.config.setdefault("WTF_CSRF_SSL_STRICT", DEFAULT_CSRF_SSL_STRICT)
> ```

I am not sure using setdefault vs. get method would provide different results with testing the CSRF extension. Are you saying using setdefault would solve this issue?

**Comment by yasunori** [comment]
I got 9 fail when run the pytest.

```
Traceback (most recent call last):
  File "/var/app/quart-wtf/.venv/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request                                     return await self.full_dispatch_request(request_context)
  File "/var/app/quart-wtf/.venv/lib/python3.10/site-packages/quart/app.py", line 1675, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/var/app/quart-wtf/.venv/lib/python3.10/site-packages/quart/app.py", line 1107, in handle_user_exception
    raise error                                                                                                                             File "/var/app/quart-wtf/.venv/lib/python3.10/site-packages/quart/app.py", line 1671, in full_dispatch_request
    result = await self.preprocess_request(request_context)                                                                                 File "/var/app/quart-wtf/.venv/lib/python3.10/site-packages/quart/app.py", line 1695, in preprocess_request                                 result = await self.ensure_async(function)()                                                                                            File "/var/app/quart-wtf/quart_wtf/csrf.py", line 59, in csrf_protect
    if not current_app.config["WTF_CSRF_ENABLED"]:                                                                                        KeyError: 'WTF_CSRF_ENABLED'
```

I got the same error 4 times .
The key of 'WTF_CSRF_ENABLED' isn't exist at the config.
Because at CSRFProtect.init_app() , it seems to be not setted 'WTF_CSRF_ENABLED'.

c.f.
https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/csrf.py#L190

I think that this fix would eliminate at least 4 errors.
I think the other 5 issues are for other reasons.

**Comment by crood58** [comment]
> I got 9 fail when run the pytest.
> 
> ```
> File "/var/app/quart-wtf/quart_wtf/csrf.py", line 59, in csrf_protect
>     if not current_app.config["WTF_CSRF_ENABLED"]:                                                                                        
> KeyError: 'WTF_CSRF_ENABLED'
> ```
> 
> I got the same error 4 times . The key of 'WTF_CSRF_ENABLED' isn't exist at the config. Because at CSRFProtect.init_app() , it seems to be not setted 'WTF_CSRF_ENABLED'.
> 
> cf. https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/csrf.py#L190
> 
> I think that this fix would eliminate at least 4 errors. I think the other 5 issues are for other reasons.

I changed the configuration variables in init_app to use "setdefault". This helped four of the tests for the CSRF extension.

**Comment by yasunori** [comment]
Thanks for confirming.

https://github.com/Quart-Addons/quart-wtf/blob/main/tests/test_csrf_extension.py#L85
This Assertion is used to verify that the extension has detected the loss of the Referrer header.

I looked up when that verify is checked.
https://github.com/Quart-Addons/quart-wtf/blob/main/quart_wtf/csrf.py#L121
```
if request.is_secure and current_app.config["WTF_CSRF_SSL_STRICT"]:
    if not request.referrer:
        self._error_response(REFERRER_HEADER)
```
It appears that the schema for access must be https.
Because `request.is_secure` must be True.

In Flask, we can use `base_url` to setting https to the test client.
cf.
https://stackoverflow.com/questions/17094110/how-do-i-unit-test-https-requests-in-flask

But `base_url` does not appear to exist in QuartClient.

I think that `sheme` keyword is useful to setting scheme to QuartClient.

```
response = await client.post("/", scheme="https", headers=headers)
```
I confirmed that when we use  `scheme="https"`, `request.is_secure` is True.

At test_csrf_extension.py, I use `scheme="https"` at L82.
And I replaced `base_url="https://localhost"` with `scheme="https"` in four places.
Then The test_csrf_extension.py test passed.

**Comment by jenish2014** [comment]
Hi, it took me awhile to figure it out but, it was needle in haystack kinda situation.

In test_form_csrf() try below code:
```
response = await client.post("/", data={"csrf_token": g.csrf_token})
                                  ^^^^
response = await client.post("/", form={"csrf_token": g.csrf_token})
```

**Comment by jenish2014** [comment]
In text_csrf_extension, I found solution to these ones:
```
async def test_error_handler(app, client):
    ...
    return error.description.lower()
                             XXXXXXX
    return error.description
    ...
```

**Comment by jenish2014** [comment]
In test_csrf_extension :
```
async def test_exempt_view(app, csrf, client):
    ...
    csrf.exempt(    "tests.test_csrf_extension.index"    ) # full path to the function passes the test
    ...
```

**Comment by crood58** [comment]
> Thanks for confirming.
> 
> https://github.com/Quart-Addons/quart-wtf/blob/main/tests/test_csrf_extension.py#L85 This Assertion is used to verify that the extension has detected the loss of the Referrer header.
> 
> I looked up when that verify is checked. https://github.com/Quart-Addons/quart-wtf/blob/main/quart_wtf/csrf.py#L121
> 
> ```
> if request.is_secure and current_app.config["WTF_CSRF_SSL_STRICT"]:
>     if not request.referrer:
>         self._error_response(REFERRER_HEADER)
> ```
> 
> It appears that the schema for access must be https. Because `request.is_secure` must be True.
> 
> In Flask, we can use `base_url` to setting https to the test client. cf. https://stackoverflow.com/questions/17094110/how-do-i-unit-test-https-requests-in-flask
> 
> But `base_url` does not appear to exist in QuartClient.
> 
> I think that `sheme` keyword is useful to setting scheme to QuartClient.
> 
> ```
> response = await client.post("/", scheme="https", headers=headers)
> ```
> 
> I confirmed that when we use `scheme="https"`, `request.is_secure` is True.
> 
> At test_csrf_extension.py, I use `scheme="https"` at L82. And I replaced `base_url="https://localhost"` with `scheme="https"` in four places. Then The test_csrf_extension.py test passed.

Thank you for your help. This helped and all the tests have now passed.

**Comment by crood58** [comment]
> Hi, it took me awhile to figure it out but, it was needle in haystack kinda situation.
> 
> In test_form_csrf() try below code:
> 
> ```
> response = await client.post("/", data={"csrf_token": g.csrf_token})
>                                   ^^^^
> response = await client.post("/", form={"csrf_token": g.csrf_token})
> ```

I made this correction and it worked. Thank you.

**Comment by crood58** [comment]
> In test_csrf_extension :
> 
> ```
> async def test_exempt_view(app, csrf, client):
>     ...
>     csrf.exempt(    "tests.test_csrf_extension.index"    ) # full path to the function passes the test
>     ...
> ```

Fixed this as well. Thank you.

**Comment by crood58** [comment]
Issue is closed all tests for CSRF extension now work.
